### ISSUE TITLE
Settings Page - Unable to change car settings after set in database

### ISSUE THREAD

**Issue by mattgar17** [henness17/AspireApp#1]
After user has input and saved car info, new options are unable to be selected.

The saved car fields are loaded properly, but are unable to be changed to a different option.

Opening an option only yields the currently selected option and no others.

Steps to reproduce:
Save a car to a user
Load the settings page
Car options should be set 
Select a field to change

**Comment by ReganTownsend** [comment]
Fixed so that when a user has submitted car data in the database and they reload settings page, the select lists will be filled with options based on their previously selected values. And their car values will be shown as selected.
