### ISSUE TITLE
Settings page - Changing previous option to 'Please select' does not update the next field

### ISSUE THREAD

**Issue by mattgar17** [henness17/AspireApp#2]
Changing a previously selected field to the 'Please select a ... ' option does not properly update the subsequent field.

Steps to reproduce:
Load the settings page
Select a year and make
Change the year field to 'Please select a year'
Make field will display 'Please select a Make'

**Comment by ReganTownsend** [comment]
Fixed so that when changing the year field back to "Please select a ...", no values will appear in the make field. Same with the other fields
